import type { Song, Artist } from "./types"

export const ARTISTS: Artist[] = [
  {
    id: "1",
    name: "Traditional",
    photoUrl: "/traditional-music-artist.jpg",
    totalSongs: 15,
    totalViews: 5000000,
  },
  {
    id: "2",
    name: "K.J. Yesudas",
    photoUrl: "/kj-yesudas-singer.jpg",
    totalSongs: 25,
    totalViews: 15000000,
  },
  {
    id: "3",
    name: "Fr. Abel",
    photoUrl: "/priest-singer.jpg",
    totalSongs: 12,
    totalViews: 3000000,
  },
  {
    id: "4",
    name: "John Newton",
    photoUrl: "/john-newton-composer.jpg",
    totalSongs: 8,
    totalViews: 20000000,
  },
  {
    id: "5",
    name: "Kester",
    photoUrl: "/christian-worship-leader.jpg",
    totalSongs: 18,
    totalViews: 8000000,
  },
  {
    id: "6",
    name: "Jyotsna",
    photoUrl: "/female-worship-singer.jpg",
    totalSongs: 14,
    totalViews: 6000000,
  },
]

export const SAMPLE_SONGS: Song[] = [
  {
    id: "1",
    title: "അത്ഭുതം കണ്ടു ഞാൻ",
    titleTransliteration: "Athbutham Kandu Njan",
    artist: ARTISTS[0],
    language: "Malayalam",
    tags: ["Worship", "Praise"],
    thumbnail: "/song-thumbnails/athbutham-kandu.jpg",
    lyrics: [
      "അത്ഭുതം കണ്ടു ഞാൻ",
      "അത്ഭുതം കണ്ടു ഞാൻ",
      "കർത്താവിന്റെ മഹത്വം",
      "അത്ഭുതം കണ്ടു ഞാൻ",
      "",
      "സ്വർഗ്ഗത്തിൽ നിന്നും വന്ന",
      "പ്രകാശം കണ്ടു ഞാൻ",
      "എന്റെ ജീവിതത്തിൽ",
      "മാറ്റം വന്നു ഞാൻ",
    ],
    chords: ["G", "D", "Em", "C", "G", "D", "C", "G"],
    originalKey: "G",
    hasVideo: true,
    videoUrl: "https://youtube.com/watch?v=example1",
    youtubeViews: 1250000,
    youtubeLikes: 45000,
    releaseDate: "2024-01-15",
    viewCount: 8500,
    trending: true,
  },
  {
    id: "2",
    title: "എന്റെ ദൈവമേ",
    titleTransliteration: "Ente Daivame",
    artist: ARTISTS[1],
    language: "Malayalam",
    tags: ["Prayer", "Devotional"],
    thumbnail: "/song-thumbnails/ente-daivame.jpg",
    lyrics: [
      "എന്റെ ദൈവമേ എന്റെ ദൈവമേ",
      "നീ എന്റെ ശക്തി",
      "നീ എന്റെ ആശ്രയം",
      "എന്റെ രക്ഷകനേ",
      "",
      "കഷ്ടതയിൽ നീ എന്നോടൊപ്പം",
      "സന്തോഷത്തിൽ നീ എന്നോടൊപ്പം",
      "എല്ലാ നാളും നീ എന്നോടൊപ്പം",
      "എന്റെ ദൈവമേ",
    ],
    chords: ["C", "G", "Am", "F", "C", "G", "F", "C"],
    originalKey: "C",
    youtubeViews: 3500000,
    youtubeLikes: 125000,
    releaseDate: "2023-06-20",
    viewCount: 15200,
    trending: false,
  },
  {
    id: "3",
    title: "स्तुति करो प्रभु की",
    titleTransliteration: "Stuti Karo Prabhu Ki",
    artist: ARTISTS[0],
    language: "Hindi",
    tags: ["Praise", "Worship"],
    thumbnail: "/song-thumbnails/stuti-karo.jpg",
    lyrics: [
      "स्तुति करो प्रभु की",
      "स्तुति करो प्रभु की",
      "उसका नाम महान है",
      "स्तुति करो प्रभु की",
      "",
      "वह हमारा उद्धारकर्ता",
      "वह हमारा रक्षक",
      "वह हमारा मित्र",
      "स्तुति करो प्रभु की",
    ],
    chords: ["D", "A", "Bm", "G", "D", "A", "G", "D"],
    originalKey: "D",
    youtubeViews: 850000,
    youtubeLikes: 32000,
    releaseDate: "2024-03-10",
    viewCount: 5600,
    trending: true,
  },
  {
    id: "4",
    title: "കർത്താവേ നിന്റെ കൃപ",
    titleTransliteration: "Karthave Ninte Kripa",
    artist: ARTISTS[2],
    language: "Malayalam",
    tags: ["Holy Communion", "Devotional"],
    thumbnail: "/song-thumbnails/karthave-kripa.jpg",
    lyrics: [
      "കർത്താവേ നിന്റെ കൃപ",
      "എന്നിൽ നിറയട്ടെ",
      "നിന്റെ സ്നേഹം എന്നിൽ",
      "എന്നും വസിക്കട്ടെ",
      "",
      "നിന്റെ വചനം എന്റെ",
      "വഴികാട്ടി ആകട്ടെ",
      "നിന്റെ ആത്മാവ് എന്നെ",
      "നയിക്കട്ടെ എന്നും",
    ],
    chords: ["G", "C", "D", "Em", "G", "C", "D", "G"],
    originalKey: "G",
    youtubeViews: 620000,
    youtubeLikes: 28000,
    releaseDate: "2023-12-05",
    viewCount: 4200,
    trending: false,
  },
  {
    id: "5",
    title: "വിവാഹ ഗീതം",
    titleTransliteration: "Vivaha Geetham",
    artist: ARTISTS[0],
    language: "Malayalam",
    tags: ["Wedding", "Celebration"],
    thumbnail: "/song-thumbnails/vivaha-geetham.jpg",
    lyrics: [
      "ഈ ദിവസം അനുഗ്രഹീതം",
      "കർത്താവ് നൽകിയ ദിവസം",
      "സ്നേഹത്തിന്റെ ബന്ധം",
      "ഇന്ന് ഉറപ്പിക്കുന്നു",
      "",
      "രണ്ടു ഹൃദയങ്ങൾ ഒന്നായി",
      "രണ്ടു ജീവിതങ്ങൾ ഒന്നായി",
      "കർത്താവിന്റെ സാന്നിധ്യത്തിൽ",
      "ഇന്ന് ചേരുന്നു",
    ],
    chords: ["C", "F", "G", "Am", "C", "F", "G", "C"],
    originalKey: "C",
    youtubeViews: 450000,
    youtubeLikes: 18000,
    releaseDate: "2023-08-15",
    viewCount: 3100,
    trending: false,
  },
  {
    id: "6",
    title: "Amazing Grace",
    titleTransliteration: "Amazing Grace",
    artist: ARTISTS[3],
    language: "English",
    tags: ["Worship", "Classic"],
    thumbnail: "/song-thumbnails/amazing-grace.jpg",
    lyrics: [
      "Amazing grace, how sweet the sound",
      "That saved a wretch like me",
      "I once was lost, but now am found",
      "Was blind, but now I see",
      "",
      "Twas grace that taught my heart to fear",
      "And grace my fears relieved",
      "How precious did that grace appear",
      "The hour I first believed",
    ],
    chords: ["G", "C", "G", "D", "G", "C", "G", "D", "G"],
    originalKey: "G",
    hasVideo: true,
    videoUrl: "https://youtube.com/watch?v=example2",
    youtubeViews: 8500000,
    youtubeLikes: 320000,
    releaseDate: "2022-04-10",
    viewCount: 25000,
    trending: false,
  },
  {
    id: "7",
    title: "என் தேவனே",
    titleTransliteration: "En Devanae",
    artist: ARTISTS[0],
    language: "Tamil",
    tags: ["Prayer", "Devotional"],
    thumbnail: "/song-thumbnails/en-devanae.jpg",
    lyrics: [
      "என் தேவனே என் தேவனே",
      "நீர் என் பலம்",
      "நீர் என் அடைக்கலம்",
      "என் இரட்சகரே",
      "",
      "துன்பத்தில் நீர் என்னோடு",
      "மகிழ்ச்சியில் நீர் என்னோடு",
      "எல்லா நாளும் நீர் என்னோடு",
      "என் தேவனே",
    ],
    chords: ["A", "E", "F#m", "D", "A", "E", "D", "A"],
    originalKey: "A",
    youtubeViews: 720000,
    youtubeLikes: 35000,
    releaseDate: "2024-02-28",
    viewCount: 6800,
    trending: true,
  },
  {
    id: "8",
    title: "నా దేవా",
    titleTransliteration: "Naa Deva",
    artist: ARTISTS[0],
    language: "Telugu",
    tags: ["Worship", "Praise"],
    thumbnail: "/song-thumbnails/naa-deva.jpg",
    lyrics: [
      "నా దేవా నా దేవా",
      "నీవు నా బలము",
      "నీవు నా ఆశ్రయము",
      "నా రక్షకుడవు",
      "",
      "కష్టములో నీవు నాతోటి",
      "సంతోషములో నీవు నాతోటి",
      "అన్ని రోజులు నీవు నాతోటి",
      "నా దేవా",
    ],
    chords: ["E", "B", "C#m", "A", "E", "B", "A", "E"],
    originalKey: "E",
    youtubeViews: 580000,
    youtubeLikes: 24000,
    releaseDate: "2023-11-20",
    viewCount: 4500,
    trending: false,
  },
  {
    id: "9",
    title: "സ്തോത്രം ആലപിക്കുവിൻ",
    titleTransliteration: "Sthothram Aalapikkuvin",
    artist: ARTISTS[4],
    language: "Malayalam",
    tags: ["Praise", "Worship"],
    thumbnail: "/song-thumbnails/sthothram-aalapikkuvin.jpg",
    lyrics: ["സ്തോത്രം ആലപിക്കുവിൻ", "കർത്താവിനെ സ്തുതിക്കുവിൻ", "അവിടുന്ന് മഹാനാകുന്നു", "സ്തോത്രം ആലപിക്കുവിൻ"],
    chords: ["D", "G", "A", "D"],
    originalKey: "D",
    youtubeViews: 2100000,
    youtubeLikes: 85000,
    releaseDate: "2024-04-05",
    viewCount: 12000,
    trending: true,
  },
  {
    id: "10",
    title: "നന്ദി നിറഞ്ഞ ഹൃദയം",
    titleTransliteration: "Nandi Niranja Hridayam",
    artist: ARTISTS[5],
    language: "Malayalam",
    tags: ["Thanksgiving", "Worship"],
    thumbnail: "/song-thumbnails/nandi-niranja.jpg",
    lyrics: ["നന്ദി നിറഞ്ഞ ഹൃദയം", "കർത്താവിനു സമർപ്പിക്കുന്നു", "അവിടുത്തെ കൃപയ്ക്കായി", "സ്തോത്രം ആലപിക്കുന്നു"],
    chords: ["C", "Am", "F", "G"],
    originalKey: "C",
    youtubeViews: 1800000,
    youtubeLikes: 72000,
    releaseDate: "2024-03-20",
    viewCount: 9500,
    trending: true,
  },
]

export const LANGUAGES = ["Malayalam", "Hindi", "Tamil", "Telugu", "Bengali", "Kannada", "English"]

export const TAGS = [
  "Worship",
  "Praise",
  "Prayer",
  "Devotional",
  "Wedding",
  "Holy Communion",
  "Celebration",
  "Classic",
  "Thanksgiving",
]

export const MUSICAL_KEYS = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
